- install/readme.md
- install/resources/cluster/kafka-project-role.yaml
- install/resources/cluster/kafka-project-rolebinding.yaml
- install/resources/cluster/kafka-topic.yaml
- install/resources/cluster/kafka.yaml
- install/resources/grafana/grafana-dashboards/strimzi-kafka-connect.yaml
- install/resources/grafana/grafana-dashboards/strimzi-kafka-exporter.yaml
- install/resources/grafana/grafana-dashboards/strimzi-kafka-mirror-maker-2.yaml
- install/resources/grafana/grafana-dashboards/strimzi-kafka.yaml
- install/resources/grafana/grafana-dashboards/strimzi-operators.yaml
- install/resources/grafana/grafana-dashboards/strimzi-zookeeper.yaml
- install/resources/grafana/grafana-datasource.yaml
- install/resources/grafana/grafana.yaml
- install/resources/operator/kafka-operator-role.yaml
- install/resources/operator/kafka-operator-rolebinding.yaml
- install/resources/operator/strimzi-pod-monitor.yaml
Add install files + guide from g-drive folder
> add kafka install guide + resources

- install/resources/monitoring-cluster/dashboards/strimzi-kafka.yaml
- install/resources/monitoring-cluster/prometheus/federation.yaml
Added federation of container_cpu related metrics
Fixed corresponding Kafka dashboard
> Fixed missing metrics and related Kafka dashboard

- README.md
Update the readme with more detailed info on the installation options
Make it easier to understand what's being done and what target makes sense to use
For anyone reviewing this, I'd recommend viewing the full fill in rendered markdown rather than the diff (https://github.com/RHCloudServices/kafka-monitoring-stuff/blob/4f5fc0bf429bb359bf78f6495f1b06ba1e0cef4d/README.md)
> Cleanup README & detail the different install options

- install/resources/monitoring-cluster/prometheus/Makefile
- install/resources/monitoring-cluster/prometheus/prometheus-rules.yaml
- install/resources/monitoring-cluster/prometheus/prometheus.yaml
Added upstream Kafka Prometheus rules to the cluster monitoring
> Added prometheus rules to cluster monitoring

- install/Makefile
- install/resources/logging/Makefile
- install/resources/logging/logging.yaml
- install/resources/logging/namespaces.yaml
- install/resources/logging/objects/dashboards.json
- install/resources/logging/objects/queries.json
- install/resources/logging/objects/visualizations.json
- install/resources/logging/operatorgroups.yaml
- install/resources/logging/subscriptions.yaml
make targets for the logging stack based on the resoruces from https://github.com/redmikhail/kafka-logging
> targets for logging stack

- .gitignore
- install/Makefile
- install/resources/logging/logging.yaml
- install/resources/monitoring-cluster/prometheus/Makefile
- install/resources/monitoring-cluster/prometheus/prometheus.yaml
- install/resources/monitoring-global/dashboards/fleet.yaml
cluster id, update fleet dashboard, fix logging node selectors
> cluster id, update fleet dashboard, fix logging node selectors

- install/resources/monitoring-cluster/dashboards/strimzi-kafka-slis.yaml
Enable line & tooltips across graphs when hovering
Easier visualising
> Use shared tooltip for easier visualising the same time across panels

- install/resources/kafka/kafka.yaml
- install/resources/monitoring-cluster/dashboards/strimzi-kafka-exporter.yaml
- install/resources/monitoring-cluster/dashboards/strimzi-kafka-slis.yaml
- install/resources/monitoring-cluster/dashboards/strimzi-kafka.yaml
- install/resources/monitoring-cluster/dashboards/strimzi-zookeeper.yaml
- install/resources/monitoring-cluster/prometheus/prometheus-rules.yaml
For @ppatierno @pb82 review/place for conversation on metrics filters
> MGDSTRM-72: first pass at kafka SLI metrics patterns

- install/resources/monitoring-cluster/dashboards/strimzi-kafka-slis.yaml
Use instant query for pods ready panels, to show correct value.
> fix pods ready panels in SLIs dashboard - instant

- install/Makefile
- install/resources/testing-chaos/Makefile
- install/resources/testing-chaos/README.md
- install/resources/testing-chaos/chaosengines/pod-delete/chaosengine.yaml
- install/resources/testing-chaos/chaosengines/pod-delete/serviceaccount.yaml
- install/resources/testing-chaos/chaosexperiments/chaosexperiments-generic.yaml
- install/resources/testing-chaos/chaosexperiments/chaosexperiments-kafka.yaml
- install/resources/testing-chaos/operator/litmus-operator-v1.8.2.yaml
https://issues.redhat.com/browse/MGDSTRM-395
Set up fault injection testing
Test the resilience of a managed kafka service by injecting faults into the service and dependent components and assessing how it can handle unexpected events.
Add resource files and make targets for the Litmus fault injection testing framework
> Add fault injection testing

- install/resources/testing-chaos/Makefile
Corrects make target error introduced from previous refactoring.
> Corrects make target

- install/Makefile
- install/resources/monitoring-cluster/prometheus/Makefile
- install/resources/monitoring-cluster/prometheus/prometheus-observatorium.yaml
- install/resources/monitoring-cluster/prometheus/prometheus.yaml
- install/resources/monitoring-cluster/promtail/Makefile
- install/resources/monitoring-cluster/promtail/config.yaml
- install/resources/monitoring-cluster/promtail/promtail.yaml
- install/resources/observatorium/Makefile
Make the Loki URL configurable and don't hardcode http for remote write.
> Configurable loki push url

- README.md
> Update readme requirements

- install/resources/testing-chaos/Makefile
Fix syntax error in make all chaos target
> update chaos target syntax

- install/Makefile
> " reverted and added back shell to makefile"

- install/resources/monitoring-global/dashboards/logs_dashboard.yaml
Signed-off-by: Swati Kale <swkale@redhat.com>
MGDSTRM-420 -Develop Fleetwide visualization/dashboards for centralized logging in Grafana
logs
using loki
> Fleet View Logs using Loki

- install/resources/kafka/kafka.yaml
> "added version for kafka and log message"

- install/resources/testing-chaos/Makefile
- install/resources/testing-chaos/README.md
Update chaos testing docs to reflect contents of repo.
> Chaos docs update

- sops/template.asciidoc
To create a place where we can put SOPs and define a template for those SOPs.
Create a sops directory and a template.asciidoc
> add sops directory and template

- sops/infra-node-pod-rebalancing.asciidoc
- sops/sharded_ingresscontroller.asciidoc
- sops/storageclass.asciidoc
- sops/yamls/mk-ingresscontroller.yaml
- sops/yamls/mk-storageclass.yaml
Adds SOPs for:
* creation of storageclass for managed kafka
* creation of ingresscontroller for managed kafka
* resolving if the infra node rebalance.
Supports new service for 90-day goal.
SOPs written.
> SOPs for storageclass, ingresscontroller and infra node rebalance.

- .gitignore
- install/resources/testing-chaos/Makefile
- install/resources/testing-chaos/chaosengines/az-down/chaosengine.yaml
- install/resources/testing-chaos/chaosengines/az-down/serviceaccount.yaml
- install/resources/testing-chaos/chaosexperiments/chaosexperiment-az-down.yaml
- install/resources/testing-chaos/utils/aws_secret_template.yaml
Add resources and make target for az-down experiment 
Az-down resources and make target will be required to add to automated testing and pipeline runs
- Add resource files required to run az-down experiment
- Add make targets to apply credentials secret for experiment
- Add make target to apply experiment definition to cluster
- Add make target to run experiment with chaosengine
> Add resources and make target for az-down experiment

- install/resources/testing-chaos/scripts/run-litmus-test.sh
https://issues.redhat.com/browse/MGDSTRM-954
This is the 1st part of the task to create a litmus testing pipeline that will make it more accessible to the team members without needing to set up and run locally.
This PR merges a bash script that will install Kafka and Litmus onto an existing OSD cluster.
> Added bash script to intall Kafka and Litmus

- install/resources/monitoring-global/dashboards/fleet.yaml
> "MGDSTRM-849:Kafka fleetwide dashboard"

- install/resources/testing-chaos/scripts/run-litmus-test.sh
https://issues.redhat.com/browse/MGDSTRM-954
Updating script to better handle erros
Adds error exit codes and feedback to the user
> Update to script to give feedback on errors.

- sops/sharded_ingresscontroller.asciidoc
- sops/yamls/mk-ingresscontroller.yaml
Add nodeplacement and validation step to ingress SOP
> add nodeplacement to ingresscontroller are validate pods are running

- sops/missing_kafka_metrics.asciidoc
Missing metrics incident
For future reference if issue reappears
Adding a SOP for missing metrics
> add sop for missing metrics

- install/resources/testing-chaos/scripts/run-litmus-test.sh
Update to pickup parameters from the pipeline that will allow users to decide if they want to install LITMUS or not.  Defaults to false on the Pipeline.
> Litmus kafka setup

- sops/sharded_ingresscontroller.asciidoc
- sops/storageclass.asciidoc
> add note that sops are outdated

- install/resources/testing-chaos/scripts/run-litmus-test.sh
Updating script to load Litmus experiments
> updating script to load Litmus experiments

- sops/update_observability_operator_cr.asciidoc
/cc @davidffrench @pb82 @david-martin
> Add SOP on how to update the observability operator CR manually

- install/resources/testing-chaos/scripts/run-litmus-test.sh
A new step has been added to wait for the litmus chaos pod running the experiment to finish
Otherwise the test script would finish before the test has finished
Adding a new extra step at the end of the script
> adding step to wait for pod-delete litmus pods to finish

- sops/replicating_sop_scenarios/corrupt_log_file.asciidoc
A place for storing the steps on how to recreate issues relating to various SOPs.
So we don't lose this information, it can be referenced in the future if required, and it can provide a basis for any potential future test automation.
> Creation of replicating SOP scenarios folder

- sops/partition_under_replicated.asciidoc
> "MGDSTRM-1060:Create SOP for when a partition is under-replicated"

- install/resources/monitoring-global/dashboards/fleet.yaml
"OR on() vector(0)" will return 0 if reponse is empty. This will ensure that output 0 retains it's color. ValueMapping for null set color to white.
> [MGDSTRM-1571] - Return 0 if empty

- README.md
- install/Makefile
Tiny fix to the `install/observability` make target.
> minor make file fix

- sops/replicating_sop_scenarios/under_replicated_partition_steps.asciidoc
future fault testing sencarios
> "MGDSTRM-1907 Create SOP for when a partition is under-replicated"

- install/resources/monitoring-global/Makefile
- install/resources/monitoring-global/dashboards/bu_usage.yaml
- install/resources/monitoring-global/dashboards/mk_usage.yaml
Create new BU usage dashboard
To help understand how extensively the service has been put through its paces
Adding a new GrafanaDashbord to the monitoring-global in the repo
> [MGDSTRM-1688] New grafana dashboard added to display BU usage metrics

- install/Makefile
- install/resources/observatorium/Makefile
- install/resources/observatorium/config-multitenant.yaml
- install/resources/observatorium/config.yaml
- install/resources/observatorium/observatorium-multitenant.yaml
Updated make targets and added sample configuration for multitenant Observatorium (MGDSTRM-2131) for prototyping
> MGDSTRM-2131: Added samples for multitenant observatorium configuration
