RHCloudServices/kafka-monitoring-stuff

README.md
install/Makefile

Create base Makefile with core installation targets :
https://issues.redhat.com/browse/MGDSTRM-164
We need a means to install our necessary workstream components within the 30-day time frame. Base Makefile to be updated with target implementations in subsequent PRs.
Add Makefile targets for the automation of the manual steps in the [current installation-guide](https://github.com/RHCloudServices/kafka-monitoring-stuff/blob/master/install/installation-guide.md)

add base Makefile with core installation targets

---

.github/PULL_REQUEST_TEMPLATE.md
install/Makefile
install/resources/cluster/kafka.yaml

Add a means to install strimzi operator to an OSD cluster via OLM. https://issues.redhat.com/browse/MGDSTRM-167
We need a way to install the strimzi operator on a cluster until the service api implementation is available
Create an OLM subscription to the strimzi-operator on the cluster
Note: this has been tested locally on a crc cluster, but not on an OSD cluster.

Add install/strimzi/operator Make target

---

install/resources/kafka/kafka.yaml

This PR just removes the Entity Operator from the `Kafka` recourse because we are not going to use it.

Removed Kafka Entity Operator

---

install/resources/monitoring-cluster/prometheus/federation.yaml
install/resources/monitoring-cluster/prometheus/prometheus.yaml
install/resources/monitoring-global/Makefile
install/resources/monitoring-global/dashboards/fleet.yaml

Adds a fleet dashboard to the global monitoring stack that shows:
* Kafka Provision success rate
* Strimzi operator version breakdown
* OpenShift version breakdown
* URLs to Strimzi clusters
* Active alerts on strimzi clusters

Fleet dashboard

---

install/resources/monitoring-cluster/dashboards/strimzi-kafka-slis.yaml

Fixed pods ready query in SLIs dashboard.
Query included pods that were not kafka broker pods or zookeeper pods.
Improved the query.

fixed pods ready query in SLIs dashboard

---

install/resources/monitoring-cluster/dashboards/strimzi-kafka-slis.yaml

Added panel to the SLIs dashboard that will show availability percentage for ready kafka and zookeeper pods.
Panels:
Query:

added availability panels for kafka and zookeeper pods

---

install/resources/testing-chaos/Makefile
install/resources/testing-chaos/chaosengines/pod-delete/chaosengine.yaml
install/resources/testing-chaos/chaosengines/pod-delete/serviceaccount.yaml

Adds ability to configure pod-delete chaos experiment

adds ability to configure chaos test targets

---

install/resources/monitoring-cluster/prometheus/federation.yaml

Downstream https://issues.redhat.com/browse/MGDSTRM-269
Numerous alerts firing due to missing metric
not included in federate list from cluster stack
add the metric to the federate config

Add missing metric to federate list for firing alerts

---

install/resources/testing-chaos/Makefile
install/resources/testing-chaos/chaosengines/pod-delete/chaosengine.yaml
install/resources/testing-chaos/chaosexperiments/chaosexperiments-generic.yaml
install/resources/testing-chaos/chaosexperiments/chaosexperiments-kafka.yaml
install/resources/testing-chaos/operator/litmus-operator-v1.8.2.yaml

Refactor litmus operator so chaos resources are deployed to litmus operator ns rather than the ns of the app under test
Separation of concerns
Update service account used by litmus operator so it has all the permissions it needs to run chaos experiments in app ns's. 
Update all chaos resources to deploy into litmus operator ns.

refactors litmus operator to run in centralised mode

---

install/resources/monitoring-cluster/prometheus/Makefile

For reusing monitoring setting in bin-packing we need to have ability to override thanos remote write url to a real remote thanos not stored on same cluster

Make thanos remote url configurable

---

install/resources/monitoring-cluster/prometheus/prometheus-rules.yaml

Use usage based & linear prediction for storage alerts instead of a fixed byte amount
This approach works regardless of the broker PV size and is based on usage rather than a set amount or a % left only.
use a combo of % calculation & predict_linear, similar to https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/storage_alerts.libsonnet#L19-L55

Replace fixed storage alerts with percentage & predictive alerts

---

install/resources/monitoring-cluster/prometheus/Makefile

Small fixes
1. Use better separator for sed expression in url replacement
2. Use non deprecated params

Use different sed separators for url

---

install/resources/monitoring-cluster/dashboards/strimzi-kafka.yaml
install/resources/monitoring-cluster/dashboards/strimzi-zookeeper.yaml

This PR updates the ZooKeeper and Kafka dashboards using the `container_cpu_usage_seconds_total` metric instead of the `container_cpu_user_seconds_total`.
It's because this metric includes the kernel CPU time other than the user one which of course has an impact on request limits for Kafka and ZooKeeper pods so it's better having them included on the graph.
It was raised even upstream in Strimzi https://github.com/strimzi/strimzi-kafka-operator/issues/3909 and fixed there https://github.com/strimzi/strimzi-kafka-operator/pull/3910
Just changing the metric name.

Using container CPU usage including kernel time

---

install/resources/kafka/kafka.yaml

Changes default logging level for zookeeper pods from INFO to WARN
Zookeeper pods seems generate excessive amount of logs on default level such as 
_2020-10-09 05:57:19,420 INFO Processing ruok command from /127.0.0.1:57132 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-2]_
Which are most likely caused by the readiness probe. Out of all logs generated from kafka cluster zookeeper pods responsible for 96% of the log entries . Recommendation is to adjust log level to WARN for zookeeper to reduce log volumes sent to Observatorium 
kafka CR now includes explicit logging definition

Set default logging level for zookeeper components to WARN

---

install/resources/testing-chaos/Makefile
install/resources/testing-chaos/strimzi-traffic-generator/deployment.yaml

https://issues.redhat.com/browse/MGDSTRM-521. Add kafka cluster traffic generation to fault tests. 
Fault tests are currently run against static kafka cluster targets without any messaging traffic.
Add deployment and make targets for go-stoker tool

Add kafka cluster traffic generation to fault tests 

---

install/resources/monitoring-cluster/prometheus/prometheus-rules.yaml

Create Error Budget burn rate alerts for:
* produce requests
* fetch(consume) requests
* tcp connections via exposed kafka routes (brokers & bootstrap round robin)
(downstream issue https://issues.redhat.com/browse/MGDSTRM-479)
Based on the rule generator at https://promtools.dev/alerts/errors

Add error budget burn alert for failed produce & consume/fetch requests

---

install/resources/monitoring-cluster/prometheus/prometheus-rules.yaml

Fix rules syntax.
This is a quick fix to unblock dev, while #50 is progressed to add rule unit tests.
errors in prometheus logs
```
level=error ts=2020-11-09T14:29:26.593Z caller=manager.go:863 component="rule manager" msg="loading groups failed" err="/etc/prometheus/rules/prometheus-kafka-prometheus-rulefiles-0/managed-services-monitoring-prometheus-kafka-prometheus-rules.yaml: 288:11: group \"kafka-api-slo\", rule 22, \"ErrorBudgetBurn_Connections\": could not parse expression: 1:55: parse error: unexpected character inside braces: ')'"
```

Fix rule syntax

---

install/Makefile
install/resources/kafka/Makefile
install/resources/kafka/kafka.yaml

This will require some dynamic logic to get the cluster dns suffix and construct the hosts.

"MGDSTRM-570:listeners for kaflka CR"

---

install/Makefile
install/resources/monitoring-cluster/prometheus/datasource.yaml
install/resources/monitoring-cluster/promtail/config.yaml
install/resources/monitoring-cluster/promtail/promtail.yaml
install/resources/observatorium/Makefile
install/resources/observatorium/observatorium.yaml
install/resources/observatorium/route.yaml

Removed most of the dynamically created kubernetes labels , removed job labels as they were constructed from redundant namespace labels and non-existent kubernetes for kafka pods name labels. 
Only logs from kafka specific components are meant to be sent to Observatorium and as result we can control set of labels needed to match log information with metrics while keeping loki metadata small and reduce cardinality of the data. Certain flexibility can be still achieved through io_strimzi_* specific kubernetes labels that are still being created using `labelmap` relabeling stanza
Config Map has been changed in  `config.yaml` and `promtail.yaml` files

Promtail conf

---

.gitignore
install/resources/testing-chaos/Makefile
install/resources/testing-chaos/chaosschedules/pod-delete-brokers/chaosschedule.yaml
install/resources/testing-chaos/chaosschedules/pod-delete-zookeepers/chaosschedule.yaml
install/resources/testing-chaos/scripts/fault-test.py

https://issues.redhat.com/browse/MGDSTRM-544
Add script to check for critical alerts when chaos experiments are running.
Validate chaos experiments being run
- Adds test script that polls prometheus for critical alerts firing when chaosschedules are run.
- Updates make targets to add test script
```
cd install/resources/testing-chaos
make all
```

Alerts fault test

---

install/resources/monitoring-cluster/promtail/promtail.yaml

Added affinity rule for promtail DaemonSet to prevent pods to be scheduled to infra nodes
Promtail DaemonSet for Onservatorium ignores taints that created on OSD infra nodes 
```
taints:
- effect: PreferNoSchedule
key: node-role.kubernetes.io/infra
```
increasing resource usage on nodes that won't be used to host kafka components . (We also potentially can have other promtail daemonset for local loki instance)
Updated DaemonSet definition in promtail.yaml file

Added affinity rule to avoid running pods on infra nodes

---

install/resources/monitoring-cluster/promtail/promtail.yaml

user our own copy of the image to circumvent docker.io rate limits

update promtail image

---

install/resources/monitoring-cluster/prometheus/federation.yaml
install/resources/monitoring-cluster/prometheus/prometheus-observatorium.yaml
install/resources/monitoring-cluster/prometheus/prometheus.yaml
install/resources/monitoring-global/Makefile
install/resources/monitoring-global/dashboards/namespace.yaml
install/resources/monitoring-global/dashboards/pod.yaml
install/resources/monitoring-global/dashboards/pv.yaml

JIRA Link: https://issues.redhat.com/browse/MGDSTRM-199
Addition of Kafka cluster - kubernetes compute metrics dashboards.
New dashbaords for namepsace level - CPU/Memory/Disk and netwrok have been created.
Creation of new Kafka cluster kubernetes compute resource metrics using USE method
Fleet wide view to see which Kafka clusters are used most and help the SRE to monitor and watch the critical compute resources.
New dashboards are added for the respective metrics

Kafka Cluster - compute metrics dashboards (USE Method)

---

sops/changing_kafka_log_verbosity.asciidoc

Document in form of SOP (standard operating procedure) steps to update initial log verbosity level identified in MGDSTRM-161  for strimzi, kafka and zookeeper components in cases

"SOP doc for kafka logging levels"

---

sops/restart-master-nodes.asciidoc

SOP for restating master node instances in AWS
This SOP is needed when AWS retires EC2 instances which contain master nodes
SOP added to sops directory

Added SOP for restarting master nodes

---

sops/restart-master-nodes.asciidoc

Add aws cli option for restarting instance
May be easier than using the aws console.
Also, you may only have access key & secret available to you rather than an IAM a/c
see PR

Add aws cli option for restarting instance

---

scripts/extend_staging_osd.sh

https://issues.redhat.com/browse/MGDSTRM-953
The current automation for extending cluster expiration uses a script in the managed-service-api repo which specifies to use a clientId and Secret for a ci user. We want to re-use the logic but use a clientToken instead, since this will avoid having to add extra roles to the ci user.
Adds the logic for the script to extend the cluster expiration but specifying a clientToken instead of a secret which pulls from vault. The automation will then run this script to extend the cluster expiration.
There will be a follow up MR against app-interface to switch the job to use this script.

add script for cluster extension

---

sops/restart-master-nodes.asciidoc

Specify to use stop-instances and start-instances instead of reboot-instances.
By specifying to use stop-instances and start-instances instead of reboot-instances.

for alt execution use stop-instances instead of reboot-instances

---

sops/accessing_kubeadmin_idp_in_osd.asciidoc

SOP to explain logging into OSD cluster with kubeadmin

---

sops/updating_observability_operator_image_in_stage.asciidoc

[MGDSTRM-1455](https://issues.redhat.com/browse/MGDSTRM-1455)
The process of rolling a new Observability Operator image to staging is very much a manual process for now and isn't documented. This SOP provides the steps to deploy and validate a new image version.

SOP for updating the observability operator image

---

install/resources/monitoring-global/dashboards/fleet.yaml

Not Ready Panel show incorrect values(Negative Integer)
There is a bug reported strimzi/strimzi-kafka-operator#4387
This change will just check for strimzi_resource_state with boolean status 0 thus it should avoid negative value.

MGDSTRM-1571 Not Ready Panel showing incorrect values in fleet dashboard

---

sops/replicating_sop_scenarios/corrupt_log_file.asciidoc
sops/skipping_kafka_record.asciidoc

[MGDSTRM-1713](https://issues.redhat.com/browse/MGDSTRM-1713)
No SOP exists for how to skip a corrupt Kafka record.
The steps for replicating a corrupt record on a Kafka cluster can be found [here](https://gist.github.com/obrienrobert/d09dd4716e44656eb202e54c59316fd6).
- Install Kafka and follow the steps in the above Gist to replicate the issue
- Use the SOP to verify that the resolution steps work as expected and the steps clear, concise and easy to understand.

Addition of SOP for skipping corrupt record

---

README.md
install/Makefile
install/resources/observability-operator/catalogue-source.yaml
install/resources/observability-operator/configmap.yaml
install/resources/observability-operator/namespace.yaml
install/resources/observability-operator/operatorgroup.yaml
install/resources/observability-operator/secrets.yaml
install/resources/observability-operator/subscription.yaml

https://issues.redhat.com/browse/MGDSTRM-1433
The Makefile currently supports installing stand alone grafana and prometheus which does not reflect the actual stack in use.
Adds a Makefile recipe for installing the observability operator with instructions for use.

add make target for observability operator

---

install/resources/observatorium/Makefile
install/resources/observatorium/minio.yaml
install/resources/observatorium/observatorium.yaml
install/resources/observatorium/operator.yaml
install/resources/observatorium/route.yaml

Some of the components of Observatorium were using **latest** tag in references to the images.Change is required to improve stability and update Observatorium version to be in sync with currently used version in Observatorium As A Service offering 
PR also includes minor modification to Observatorium Makefile to automatically populate observatorium API route

MGDSTRM-1443 - Updated versions of Observatorium images

---

install/resources/monitoring-global/dashboards/mk_usage.yaml

Updates Prometheus queries on the 3 Openshift Clusters panels
The Previous expression was failing when calculating the number of Openshift clusters. 
The panels couldn't display any info.
Changing the Prometheus queries.

MGDSTRM-2452
